// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF20irLbSuEizK9msbbnUdqdJW5QEnVhQ',
    appId: '1:320731707254:web:f4d4dcda93debb09a8ec57',
    messagingSenderId: '320731707254',
    projectId: 'financeiroapp-1b0c1',
    authDomain: 'financeiroapp-1b0c1.firebaseapp.com',
    storageBucket: 'financeiroapp-1b0c1.firebasestorage.app',
    measurementId: 'G-GSF7BG2SNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVB4VVY6IiA821YXGntqrjdKtCr4EZyx4',
    appId: '1:320731707254:android:3159e56d6efa4913a8ec57',
    messagingSenderId: '320731707254',
    projectId: 'financeiroapp-1b0c1',
    storageBucket: 'financeiroapp-1b0c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsA7WdeFNKSfYWfYJ4E2xAysTD5WrZr7k',
    appId: '1:320731707254:ios:9fca5fdbd2a8daa6a8ec57',
    messagingSenderId: '320731707254',
    projectId: 'financeiroapp-1b0c1',
    storageBucket: 'financeiroapp-1b0c1.firebasestorage.app',
    iosBundleId: 'com.example.financeiroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsA7WdeFNKSfYWfYJ4E2xAysTD5WrZr7k',
    appId: '1:320731707254:ios:9fca5fdbd2a8daa6a8ec57',
    messagingSenderId: '320731707254',
    projectId: 'financeiroapp-1b0c1',
    storageBucket: 'financeiroapp-1b0c1.firebasestorage.app',
    iosBundleId: 'com.example.financeiroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF20irLbSuEizK9msbbnUdqdJW5QEnVhQ',
    appId: '1:320731707254:web:b334d1fde47058d1a8ec57',
    messagingSenderId: '320731707254',
    projectId: 'financeiroapp-1b0c1',
    authDomain: 'financeiroapp-1b0c1.firebaseapp.com',
    storageBucket: 'financeiroapp-1b0c1.firebasestorage.app',
    measurementId: 'G-SRKEC0VCX8',
  );

}